FROM env:latest

COPY finetune.py .

CMD python3 finetune.py \
  --pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4 \
  --dataset_name=KhangTruong/NWPU_Split \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --mixed_precision="bf16" \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="finetuned" 
